version: '3.6'
services:
  react:
    env_file:
      - .env
    volumes:
      - ./app:/project
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"